# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4105e8018832f7a75bbe791384f5f1c7577bf2087e73c322f721d2b2a9ceb6d5d5098590806eb827e8b337caba581de0fcc5a76a1300d34518f48b09563f244

test:
  secret_key_base: 41f9fd0606ae5882033c2433239234793412d5223b78114b2ae4c369c451ef01d71066e4d1c57a822bc3e48c40722d494977ba8f1147175f6db1282a00ec3f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
